### ISSUE TITLE
Script hangs

### ISSUE THREAD

**Issue by adieyal** [Code4SA/gazettes-liquor-extractor#1]
The test script hangs on line 27

**Comment by boolbag** [comment]
Hi Adi, L here (but please use the github nick on this account instead of real name), nice to see you.

The initial script was for Python 3, but it looks like someone modified the entry point for Python 3 (`print` no longer a function) so all bets are off. For instance, one problem is that the `print_licensee()` calls in that file will use the `print()` function. Not sure about any other translation conflicts. So my question to you is whether Python 2 is necessary. 

**Edit:** The cloned repo works for me as-is in a virtualenv with 2.7.12

**Comment by adieyal** [comment]
Python 2 isn't necessary - print is just a habit. Not sure why it doesn't work on my side with 2.7.10 but the updated code works so this issue is no longer relevant.
